import { useState, useEffect, useRef } from 'react'
import { supabase, isSupabaseConfigured } from '../lib/supabase'
import { toISODate } from '../lib/tasks'

/* The morning brief as a dashboard card (not a fleeting push). Once per day, at
   or after the user's chosen send time, it's generated by the `morning-brief`
   function and cached locally — it then lives at the top of the dashboard until
   dismissed. Regenerates on a new day; survives reloads within the day. */
const KEY = 'sentinel.brief.v1'

const readCache = () => {
  try { return JSON.parse(localStorage.getItem(KEY) || 'null') } catch { return null }
}
const writeCache = (rec) => {
  try { localStorage.setItem(KEY, JSON.stringify(rec)) } catch { /* non-fatal */ }
}

// Is the local clock at or past "HH:MM"?
const pastTime = (hhmm) => {
  const [h, m] = String(hhmm || '07:00').split(':').map(Number)
  const now = new Date()
  return now.getHours() * 60 + now.getMinutes() >= (h || 0) * 60 + (m || 0)
}

export default function useMorningBrief({ enabled, briefTime }) {
  const [text, setText] = useState(null)
  const [dismissed, setDismissed] = useState(false)
  const [loading, setLoading] = useState(false)
  const [tick, setTick] = useState(0)   // bumped by refresh() to force a regenerate
  const genStarted = useRef(false)

  useEffect(() => {
    if (!enabled || !isSupabaseConfigured) { setText(null); setDismissed(false); return }
    const today = toISODate(new Date())
    const cache = readCache()

    // Same-day cache — reuse text and dismissed state, don't regenerate.
    if (cache?.date === today) {
      setText(cache.text || null)
      setDismissed(Boolean(cache.dismissed))
      if (cache.text || cache.dismissed) return
    } else {
      setText(null); setDismissed(false)
    }

    // Only generate once it's the user's brief time (or later) today.
    if (!pastTime(briefTime) || genStarted.current) return
    genStarted.current = true
    setLoading(true)
    ;(async () => {
      try {
        const tz = Intl.DateTimeFormat().resolvedOptions().timeZone
        const { data, error } = await supabase.functions.invoke('morning-brief', { body: { tz, today } })
        if (error || data?.error) throw new Error(data?.error || error?.message || 'brief failed')
        writeCache({ date: today, text: data.brief, dismissed: false })
        setText(data.brief)
        setDismissed(false)
      } catch (e) {
        console.error('morning brief failed:', e)
        genStarted.current = false   // let a later load retry
      } finally {
        setLoading(false)
      }
    })()
  }, [enabled, briefTime, tick])

  // Throw away today's cached brief and generate a fresh one (e.g. plans changed,
  // or tasks were knocked out since the morning).
  const refresh = () => {
    try { localStorage.removeItem(KEY) } catch { /* non-fatal */ }
    genStarted.current = false
    setText(null)
    setTick(t => t + 1)
  }

  const dismiss = () => {
    const today = toISODate(new Date())
    const cache = readCache() || {}
    writeCache({ ...cache, date: today, text: text ?? cache.text ?? '', dismissed: true })
    setDismissed(true)
  }

  const show = Boolean(enabled) && !dismissed && (loading || Boolean(text))
  return { brief: text, loading, show, dismiss, refresh }
}
